### ISSUE TITLE
每次关闭浏览器都要重新输入exKey

### ISSUE THREAD

**Issue by Zackyooo** [ehpanda/expanda.org#10]
您好，目前我的问题就是标题里所说的。我使用了自己的exkey之后，每次登陆都要重新输入，有没有什么一劳永逸的方法

**Comment by noprogramming** [comment]
您油猴安装的是公共书签或者52linglong的镜像版书签，从expanda.org进入每次都会写入公共账号覆盖掉之前的COOKIE。
解决方法是删除油猴已安装的书签，在expanda.org输入exkey点确定，生成私人书签，再按流程安装到油猴。这样每次打开加载的都是自己的账号了。
