### ISSUE TITLE
新版脚本不支持暴力猴，还望支持。

### ISSUE THREAD

**Issue by ningsibuqu** [ehpanda/expanda.org#11]
原来旧版脚本搭配暴力猴中可以正常试用，更新脚本后就失效了，无法转跳。
https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag
暴力猴版本2.12.1
熊猫书签版本V16

**Comment by noprogramming** [comment]
已修复，暴力猴对网址schema采取了严格匹配模式，加上就好了。
烦请更新到V17，非常感谢反馈！

**Comment by FUXIANGEN** [comment]
已更新V17,现在访问
https://exhentai.org/favicon.ico
倒是有检测到脚本的运行，但是依旧无法转跳。

**Comment by FUXIANGEN** [comment]
检测不到V17的更新…
https://panda.52linglong.com/panda.user.js

**Comment by FUXIANGEN** [comment]
不过已手动加上*:// 
已恢复正常。

**Comment by ningsibuqu** [comment]
再次感谢！
