### ISSUE TITLE
E站还会回收里站权限吗？

### ISSUE THREAD

**Issue by nazhendenb** [ehpanda/expanda.org#12]
我的号以前能进， 今天改了个密码之后就进不去了。用的是QQ邮箱 欧美IP， 付费机场，应该算是公共IP吧

**Comment by nazhendenb** [comment]
注册邮箱是QQ邮箱，欧美IP 19年8月注册的

**Comment by nazhendenb** [comment]
我的号今天在改了密码之后出现了这种情况：传统方法（先删除cookie，然后登录表站，再登录里站）的话就会进不去里站，查cookie发现igneous的值是mystery，我之前注册过好几个号，没有权限的账号都是mystery
如果用改cookie的方法（用熊猫书签效果也是一样），（我保存了旧cookie） 能进里站，但是一旦访问“favorites”“setting”“my uploads”“”my tags“，左上角就会出现三个字母：err，然后其他部分都是白屏
请问您之前有见过这种情况吗？如果有的话该如何解决？

**Comment by noprogramming** [comment]
里站会对已获取权限的账号用户id、密码hash、igneous进行缓存，三者比对一致就可以进里站，但设置一类还需要账号保持可用状态。书签这号就是已经失效的，用的以前的COOKIE缓存所以还能进。
您个人账号同样的情况，改COOKIE能进只是因为以前的缓存，现在点设置出现“err”说明账号已经没有权限了。

E站改密码后会重新同步表里站账号数据，在这过程中里站权限可能会失效，原因：
1. 它的账号同步还未进行，这个可能两周进行一次，所以再等半个月说不定就能进了。
2. 账号同步已经进行了，但在同步时你的账号被过滤器屏蔽了，原因可能是用了QQ邮箱。这种悲剧了，你的账号权限就没了。

所以先等两周看看，清空浏览器COOKIE，别开启书签油猴，先登录表站，再登录里站。如果还不能用那权限就没了，就再注册个号吧……

**Comment by nazhendenb** [comment]
> 里站会对已获取权限的账号用户id、密码hash、igneous进行缓存，三者比对一致就可以进里站，但设置一类还需要账号保持可用状态。书签这号就是已经失效的，用的以前的COOKIE缓存所以还能进。
> 您个人账号同样的情况，改COOKIE能进只是因为以前的缓存，现在点设置出现“err”说明账号已经没有权限了。
> 
> E站改密码后会重新同步表里站账号数据，在这过程中里站权限可能会失效，原因：
> 
> 1. 它的账号同步还未进行，这个可能两周进行一次，所以再等半个月说不定就能进了。
> 2. 账号同步已经进行了，但在同步时你的账号被过滤器屏蔽了，原因可能是用了QQ邮箱。这种悲剧了，你的账号权限就没了。
> 
> 所以先等两周看看，清空浏览器COOKIE，别开启书签油猴，先登录表站，再登录里站。如果还不能用那权限就没了，就再注册个号吧……

 首先感谢您上次对我问题的解答，现在我又有问题来请教您了。

我上周把系统语言、浏览器语言都改成了英文，时区也改成了英国，换了两次节点注册了两个号，并且邮箱也是用微软的outlook，然后昨天晚上用PC登录的时候（此时已经改成了中文环境）发现igneous的值不是mystery，也就是说有权限了。然后我在安卓的EhViewer上登录，登上去就发现igneous变成了mystery，然后第二天我在电脑上登的时候发现igneous确实变成了mystery，但是这期间我并没有改密码，请问为什么我还会被回收权限？    

另外还有一点， 为什么那些上古老号（数字ID前300万，因为我看到里站有一条说是前两档画质只提供给ID前300万的）即使是用QQ邮箱，大陆IP，改了密码也不会被回收权限？

最后再问个题外话，如果在表站上传自己买的CG、或者是在论坛活跃发言，会不会得到权限?

**Comment by noprogramming** [comment]
账号申请下来两周都不一定给权限，更别说一周了。他们权限发放是手动的，具体看站长心情。您说有ig值是通过官网登录已经顺利进里站了？如果没有建议先用官网方法试试，别刚注册就用ehviewer这类第三方软件。

老号确实权限高，以前即便QQ注册也不会收回，这规则只对新注册的账号，当然不能用QQ邮箱也是一年前的了，现在怎样也说不好。至于画质，只有预览图和原图两档，有权限就能看，这个没有区别的。

最后一个当然，官方欢迎各路贡献，以前申请带权限号就是去论坛发帖。

**Comment by nazhendenb** [comment]
是的，我通过官方方法(删除cookie，进表站，进里站)成功进入里站了，然后在EhViewer登录了一次，第二天ig值又变成mystery了，我认为原因不在第三方APP，而是因为我手机的系统语言 地区都是大陆的

**Comment by noprogramming** [comment]
我手机浏览器语言地区也是大陆的，书签（就是访问官网）登录从来没出过问题。
感觉可能是EHV登录，新号出现了异地IP登录（EHV服务器登录IP和你不一致），然后被发现就封了。

**Comment by noprogramming** [comment]
您好我是新来的开发负责人，这个问题也有可能是E站针对IP的主动限制。
这种情况下即便可以获得权限，当检测到IP地址为受限时，一样会设置ig为yay拦截。
今天更新的书签遇到白屏时会尝试强制写入，您可以试试把COOKIE作为exkey绑定到书签登录。

**Comment by aafeng2135468** [comment]
e站的权限怎么获取？
我的ig显示null是什么意思？

**Comment by 10tsukasa10** [comment]
您好，我想请问一下，我从注册账号开始就能进里站，在昨天在里站看本子的时候突然遇到了问题。点开本子之后会显示《解析失败》，但是其他所有功能都正常。切换到表站之后本子可以正常浏览。但是切换到里站出来点进去本子是解析失败之外其余功能都正常，igneous显示也是正常的，不是mystery。这种是什么问题呢？

**Comment by hohenfraniz** [comment]
> 您好，我想请问一下，我从注册账号开始就能进里站，在昨天在里站看本子的时候突然遇到了问题。点开本子之后会显示《解析失败》，但是其他所有功能都正常。切换到表站之后本子可以正常浏览。但是切换到里站出来点进去本子是解析失败之外其余功能都正常，igneous显示也是正常的，不是mystery。这种是什么问题呢？

同一个问题

**Comment by lxh2000lxh** [comment]
> 您好，我想请问一下，我从注册账号开始就能进里站，在昨天在里站看本子的时候突然遇到了问题。点开本子之后会显示《解析失败》，但是其他所有功能都正常。切换到表站之后本子可以正常浏览。但是切换到里站出来点进去本子是解析失败之外其余功能都正常，igneous显示也是正常的，不是mystery。这种是什么问题呢？

我也是这样，网页可以，但用app就不行
