### ISSUE TITLE
油猴脚本，竖屏看图功能无限报错”网络错误，是否重试？“

### ISSUE THREAD

**Issue by CRH5-091A** [ehpanda/expanda.org#20]
ex里站已登录。油猴插件显示脚本已激活。chrome版本80.0.3987.149。
chrome控制台报错信息为
Access to XMLHttpRequest at 'https://e-hentai.org/g/1590371/d1a4c2136c/?p=0' from origin 'https://exhentai.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by noprogramming** [comment]
看了下传统模式没这问题，不知道是不是油猴版本过低导致的？
我装了同样版本的浏览器，待会去试试。

**Comment by noprogramming** [comment]
Chrome 80.0.3987.149
Tampermonkey 4.9
测试没问题，楼主的详细情况是？
E站已登录还是非登录？exkey有否绑定？

**Comment by CRH5-091A** [comment]
油猴版本同4.9，e站已登录且能进入里站，刚才我也试了一下传统模式是可以使用的，但是油猴依然报错。有一点我没明白，是否需要设置该插件的包括/匹配网址？因为我发现不设置的话在e站内插件是不激活的。还有一点疑问就是在传统模式中通过setAttribute语句写入了exkey的值，而脚本的js代码里则没有这句，我不太懂这里是怎么实现的exkey的绑定
![TIM图片20200324025253](https://user-images.githubusercontent.com/62252971/77352713-95823e80-6d7a-11ea-8850-8461f0ecae24.png)

**Comment by noprogramming** [comment]
看您用的52linglong网的版本，他那是第三方镜像，好久没更新了，不知有啥问题。建议用我们站的：https://expanda.org
按照流程走一下试试，绑定exkey流程是先在书签生成页填写exkey，再复制的代码即是绑定后的书签。原理是书签解析exkey再向E站注入COOKIE。
不填exkey生成的就是公共书签，如果公号被封就没法用了。

**Comment by CRH5-091A** [comment]
问题解决了 十分感谢您的帮助 谢谢

**Comment by noprogramming** [comment]
客气了，那我关帖了。
