### ISSUE TITLE
公共书签失效

### ISSUE THREAD

**Issue by dango1dango1** [ehpanda/expanda.org#21]
请问公共书签是否失效了，能抢救吗？

**Comment by noprogramming** [comment]
是的，被封了，正在问几个大佬还有没有能用的号。

**Comment by dango1dango1** [comment]
有什么支持你们的途径吗，没有技术，只有给一点点资金的能力，表示感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"noprogramming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上11:53
收件人:&nbsp;"noprogramming/expanda"<expanda@noreply.github.com&gt;;
抄送:&nbsp;"团子"<3060594645@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [noprogramming/expanda] 公共书签失效 (#21)





 
是的，被封了，正在问几个大佬还有没有能用的号。

**Comment by noprogramming** [comment]
> 
> 有什么支持你们的途径吗，没有技术，只有给一点点资金的能力，表示感谢。
> 
感谢，资金这个真不用，书签这我从上一任管理大佬接手的，CDN都是白嫖的。
每年开销就一个域名钱，他给我的域名账户里足够撑10年的了……
现在主要是缺少公共账号资源，有点难搞。

**Comment by dango1dango1** [comment]
是的，上次账号被封大概是两年前了吧，公共账号资源是真的越来越难找了。
---原始邮件---
发件人:"noprogramming"<notifications@github.com>;
发送时间:2020年3月24日(星期二) 凌晨0:14
收件人:"noprogramming/expanda"<expanda@noreply.github.com>;
抄送人:"dango1dango1"<3060594645@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [noprogramming/expanda] 公共书签失效 (#21)



  
有什么支持你们的途径吗，没有技术，只有给一点点资金的能力，表示感谢。
  
感谢，资金这个真不用，书签这我从上一任管理大佬接手的，CDN都是白嫖的。
 每年开销就一个域名钱，他给我的域名账户里足够撑10年的了……
 现在主要是缺少公共账号资源，有点难搞。
 
&mdash;
