### ISSUE TITLE
公共书签即将告罄

### ISSUE THREAD

**Issue by noprogramming** [ehpanda/expanda.org#22]
官方书签：https://expanda.org
不能用的应该是第三方镜像，他们没更新。

昨天公号被封了，现在手头已经没有可用的公共号。
拿原图的号苟延残喘了一下，不知能坚持多久。
如果以后全都被封，那各位只能用私号了。

“exkey”是上位开发者为了编程方便的叫法，并非E站官方称呼。
以后统一改称“密钥”或“COOKIE”，这样表述更加准确。

**Comment by dango1dango1** [comment]
现在熊猫是不是无法注册里站了

**Comment by E1evenS9ark** [comment]
意思是没有公私号都没有了，里站永远也上不去了？

**Comment by noprogramming** [comment]
> 现在熊猫是不是无法注册里站了

这个不知道，我这些账号都是老开发者给的，就是他那也没号了。按照说明写的注册应该能获取权限，但是要求太苛刻了，比如海外家用IP的VPN没几个人能搞到的。

**Comment by noprogramming** [comment]
> 意思是没有公私号都没有了，里站永远也上不去了？

私号是自己注册的，不受影响，除非以后新版浏览器限制COOKIE注入机制。

公号目前手头最后一个凑合用着，再封掉就没了。我注册了几个，但不知能不能获取到权限。

不存在“里站永远也上不去了”，有自己的账号在表站登录就能进里站，书签只是个第三方辅助，垮掉和E站官方没关系。

**Comment by mengshanasi** [comment]
请问新的公共号可以用了吗？我用油猴脚本和传统的点两次书签的方法想进ex站，还是要求我填key

**Comment by 985363253** [comment]
加油

**Comment by suibianqugeming1** [comment]
难受~

**Comment by 382481733** [comment]
大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）

**Comment by noprogramming** [comment]
> 
> 
> 请问新的公共号可以用了吗？我用油猴脚本和传统的点两次书签的方法想进ex站，还是要求我填key

用的是 https://expanda.org 这个书签吗？这个更新了可以用。
第三方镜像站我就不知道了。

**Comment by noprogramming** [comment]
> 
> 
> 大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）

密钥不是有了，然后打开 https://expanda.org 这个首页不是有个输入密钥吗，
输进去，然后再点“油猴”或者“传统”，重新安装绑定密钥后的书签。
这样安装用的就不是公共号了，而是你自己的号。

**Comment by mengshanasi** [comment]
我也把私号搞出来了，感谢大佬。

**Comment by mengshanasi** [comment]
我用公共号打开了ex站，然后按https://expanda.org 的教程把各个变量都填好组成了key，用是可以用的，但因为我没有按教程的第一步那样用vpn上ex站而是用公共号，那我这样弄出来的key是我的私人号还是仍然是公共号呢？

**Comment by 382481733** [comment]
> > 大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）
> 
> 密钥不是有了，然后打开 https://expanda.org 这个首页不是有个输入密钥吗，
> 输进去，然后再点“油猴”或者“传统”，重新安装绑定密钥后的书签。
> 这样安装用的就不是公共号了，而是你自己的号。
我试了下 提示没有权限。。。是不是我当时注册账号的时候 邮箱的问题还是？唉。。果然还是只能用公共的了嘛

**Comment by E1evenS9ark** [comment]
找不到[Edge] Debug-Cookie-exhentai.org

[Chrome] Application-Cookies-exhentai.org

[Firefox] Storage-Cookies-exhentai.org
这是为什么呢

**Comment by noprogramming** [comment]
> 
> 
> 我用公共号打开了ex站，然后按https://expanda.org 的教程把各个变量都填好组成了key，用是可以用的，但因为我没有按教程的第一步那样用vpn上ex站而是用公共号，那我这样弄出来的key是我的私人号还是仍然是公共号呢？

当然是公号……这样搞并无卵用，不过步骤是对的。
你得自己注册账号然后按正常方式打开一遍E站才行，说实话能搞下来脱离书签也能进里站了，到时书签纯粹变成了看图辅助。

**Comment by noprogramming** [comment]
> 
> 
> > > 大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）
> > 
> > 
> > 密钥不是有了，然后打开 https://expanda.org 这个首页不是有个输入密钥吗，
> > 输进去，然后再点“油猴”或者“传统”，重新安装绑定密钥后的书签。
> > 这样安装用的就不是公共号了，而是你自己的号。
> > 我试了下 提示没有权限。。。是不是我当时注册账号的时候 邮箱的问题还是？唉。。果然还是只能用公共的了嘛

你是在里站提取的COOKIE还是在表站提取的？
如果是里站的话，没有权限咋进的里站？
表站提取的拿来用，提示没有权限，那就是没有权限了，放两周再试试吧。

**Comment by noprogramming** [comment]
> 
> 
> 找不到[Edge] Debug-Cookie-exhentai.org
> 
> [Chrome] Application-Cookies-exhentai.org
> 
> [Firefox] Storage-Cookies-exhentai.org
> 这是为什么呢

你是啥浏览器，比如 Chrome ，用正常方法登录进里站以后打按 F12 打开控制台，找这些。

**Comment by 382481733** [comment]
> > > > 大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）
> > > 
> > > 
> > > 密钥不是有了，然后打开 https://expanda.org 这个首页不是有个输入密钥吗，
> > > 输进去，然后再点“油猴”或者“传统”，重新安装绑定密钥后的书签。
> > > 这样安装用的就不是公共号了，而是你自己的号。
> > > 我试了下 提示没有权限。。。是不是我当时注册账号的时候 邮箱的问题还是？唉。。果然还是只能用公共的了嘛
> 
> 你是在里站提取的COOKIE还是在表站提取的？
> 如果是里站的话，没有权限咋进的里站？
> 表站提取的拿来用，提示没有权限，那就是没有权限了，放两周再试试吧。

我大概明白了。。我把我的情况完整的说下吧。我最开始弄的帐号就是表站注册的（那个时候表站我在家还不用挂梯子），很多很多年前了。在知道了里站之后，当时搜索了很多办法，其中一个就是把表站的帐号cookie弄到里站去然后等几周就好了。我用的就是那个办法，从那之后，就算表站要梯子进，里站都不用梯子。直到前几天，我的表站和里站都进不去了，不管挂不挂梯子都是白屏，于是我就找到了熊猫书签。。再然后就是上面说的事情了。。

**Comment by noprogramming** [comment]
> 
> 
> > > > > 大佬 我按要求把我的秘钥按教学格式弄出来了，但是后续不知道咋搞啊 求助！！有偿（我的里站之前一直不挂梯子也能进 表站要挂梯子，很早很早注册的帐号，现在感觉好麻烦啊）
> > > > 
> > > > 
> > > > 密钥不是有了，然后打开 https://expanda.org 这个首页不是有个输入密钥吗，
> > > > 输进去，然后再点“油猴”或者“传统”，重新安装绑定密钥后的书签。
> > > > 这样安装用的就不是公共号了，而是你自己的号。
> > > > 我试了下 提示没有权限。。。是不是我当时注册账号的时候 邮箱的问题还是？唉。。果然还是只能用公共的了嘛
> > 
> > 
> > 你是在里站提取的COOKIE还是在表站提取的？
> > 如果是里站的话，没有权限咋进的里站？
> > 表站提取的拿来用，提示没有权限，那就是没有权限了，放两周再试试吧。
> 
> 我大概明白了。。我把我的情况完整的说下吧。我最开始弄的帐号就是表站注册的（那个时候表站我在家还不用挂梯子），很多很多年前了。在知道了里站之后，当时搜索了很多办法，其中一个就是把表站的帐号cookie弄到里站去然后等几周就好了。我用的就是那个办法，从那之后，就算表站要梯子进，里站都不用梯子。直到前几天，我的表站和里站都进不去了，不管挂不挂梯子都是白屏，于是我就找到了熊猫书签。。再然后就是上面说的事情了。。

那就是自己的账号没法用了，登进去白屏就代表丧失了里站权限（以前是熊猫），可能因为账号被封或者权限被取消（E站定期会取消一些没有分享值的账号）。
书签这个只不过是辅助写入COOKIE，和你原来手动修改COOKIE原理是一样的，如果原来账号没法用那书签绑定也没用。可以考虑注册个新号，目前先凑合用公共号吧。

**Comment by Auzzaue** [comment]
有人遇到過cookie裡有ipb_pass_hash、ipb_member_id就是沒有igneous的情況嗎

**Comment by JCX8362** [comment]
> 有人遇到過cookie裡有ipb_pass_hash、ipb_member_id就是沒有igneous的情況嗎

你的賬號沒有權限，重新註冊吧

**Comment by tony0730** [comment]
我是用美国节点用谷歌邮箱注册的还没到一个星期的权限赋予，igneous一栏显示为mystery，出现这个情况是不是没有权限？

**Comment by liuhua424** [comment]
书签用不了了吗？今天凌晨1点的时候用书签进去了，但晚上来试的时候发现又进不去了，之后又重新试，发现在要输入cookie的界面时候，不管我是保持空的点确定，还是用注册的cookie组合输入进去，最后窗口还是会反复弹出输入cookie界面，进不去里站。。。。。

**Comment by JCX8362** [comment]
> 我是用美国节点用谷歌邮箱注册的还没到一个星期的权限赋予，igneous一栏显示为mystery，出现这个情况是不是没有权限？

還沒有權限，再等一等吧

**Comment by 1372501421** [comment]
神了   我的私人key今天也进不去了

**Comment by 1372501421** [comment]
神了  我的私人key今天也进不去了

**Comment by mengshanasi** [comment]
> 
> 
> > 我用公共号打开了ex站，然后按https://expanda.org 的教程把各个变量都填好组成了key，用是可以用的，但因为我没有按教程的第一步那样用vpn上ex站而是用公共号，那我这样弄出来的key是我的私人号还是仍然是公共号呢？
> 
> 当然是公号……这样搞并无卵用，不过步骤是对的。
> 你得自己注册账号然后按正常方式打开一遍E站才行，说实话能搞下来脱离书签也能进里站了，到时书签纯粹变成了看图辅助。

私人密匙是绑定一台电脑的吗？假如我家里两台电脑，其中一台上搞了私人密匙，那另一台电脑也能用这个密匙吗？

**Comment by changan931114** [comment]
你好，我试图制作私人书签，大概是
ipb_pass_hashipb_member_idxigneous的格式对吗？
但是不知道为什么，申请私人书签无效，进入网站时会反复弹出
无权访问，更换exkey的提示，直接将私人书签ID输入也没有效果
请问我的格式有问题吗？还是说现在书签暂时不能使用呢？

**Comment by liuhua424** [comment]
> 你好，我试图制作私人书签，大概是
> ipb_pass_hashipb_member_idxigneous的格式对吗？
> 但是不知道为什么，申请私人书签无效，进入网站时会反复弹出
> 无权访问，更换exkey的提示，直接将私人书签ID输入也没有效果
> 请问我的格式有问题吗？还是说现在书签暂时不能使用呢？

俺也是这样

**Comment by Potato32** [comment]
### **_ @noprogramming 我联系到站点管理员了, 快点！告诉我公共账号的用户名。
至少不用等那么久再注册一个。快点！_**

**Comment by luoyangyang2001** [comment]
创建私人账号时找不到igneous是怎么回事

**Comment by changan931114** [comment]
> 创建私人账号时找不到igneous是怎么回事

igneous是在EX界面才有，EH没有的，而且新账号一周内igneous是无效的

**Comment by luoyangyang2001** [comment]
但是不找到igneous制作熊猫书签我怎么进入ex界面呢，大佬求指导

**Comment by luoyangyang2001** [comment]
> > 创建私人账号时找不到igneous是怎么回事
> 
> igneous是在EX界面才有，EH没有的，而且新账号一周内igneous是无效的

但是不找到igneous制作熊猫书签我怎么进入ex界面呢，大佬求指导

**Comment by changan931114** [comment]
> > > 创建私人账号时找不到igneous是怎么回事
> > 
> > 
> > igneous是在EX界面才有，EH没有的，而且新账号一周内igneous是无效的
> 
> 但是不找到igneous制作熊猫书签我怎么进入ex界面呢，大佬求指导

注册账号后，等七天，直接进入EX，这个时候大概率是白屏，然后F12，查COOKEY，然后里面就能看到igneous了

**Comment by Minepig** [comment]
我想问一下，如果私人账户获取权限成功了，有没有什么行为会导致权限失效的
好不容易弄好的账号不想白给

顺便证实一下现在里站还是可以注册的，就是很困难

**Comment by Minepig** [comment]
> > > 我用公共号打开了ex站，然后按https://expanda.org 的教程把各个变量都填好组成了key，用是可以用的，但因为我没有按教程的第一步那样用vpn上ex站而是用公共号，那我这样弄出来的key是我的私人号还是仍然是公共号呢？
> > 
> > 
> > 当然是公号……这样搞并无卵用，不过步骤是对的。
> > 你得自己注册账号然后按正常方式打开一遍E站才行，说实话能搞下来脱离书签也能进里站了，到时书签纯粹变成了看图辅助。
> 
> 私人密匙是绑定一台电脑的吗？假如我家里两台电脑，其中一台上搞了私人密匙，那另一台电脑也能用这个密匙吗？

应该是可以的，密钥就是你的cookie，书签的作用是注入cookie让你恢复登录，如果你家两台电脑是在同一局域网下那对于e站来说就是同一台电脑

**Comment by Scandy18** [comment]
老帐号没有进里站的资格，只能按部就班重新注册然后等7天了，害

**Comment by DavidXie03** [comment]
大佬们，我想问一下注册账号中要求的“拥有私人ip的欧美vpn”是什么意思，关于这点除了挂欧美vpn以外还需要什么操作？小白不胜感激

**Comment by Namenots** [comment]
以前19年注册的账号直到这几天前都是OK的，但是最近这几天开始传统方法和油猴脚本都上不去了，请问是什么原因导致的？账号失效？浏览器更新？代码更新导致失效？还是E站本身更新了机制 
求救

**Comment by 1372501421** [comment]
> 以前19年注册的账号直到这几天前都是OK的，但是最近这几天开始传统方法和油猴脚本都上不去了，请问是什么原因导致的？账号失效？浏览器更新？代码更新导致失效？还是E站本身更新了机制
> 求救

巧了   我的也是这几天上不去的  老账号翻了一下好像已经没有igneous了好像

**Comment by ghost** [comment]
我一个18年注册的号 Gmail的 就从来没有进去过 不知道真的是不是注册ip的问题

**Comment by luoyangyang2001** [comment]
> > > > 创建私人账号时找不到igneous是怎么回事
> > > 
> > > 
> > > igneous是在EX界面才有，EH没有的，而且新账号一周内igneous是无效的
> > 
> > 
> > 但是不找到igneous制作熊猫书签我怎么进入ex界面呢，大佬求指导
> 
> 注册账号后，等七天，直接进入EX，这个时候大概率是白屏，然后F12，查COOKEY，然后里面就能看到igneous了

按方法找到igneous为mystery，是时间没到的过么已经等了6天

**Comment by Namenots** [comment]
> > 以前19年注册的账号直到这几天前都是OK的，但是最近这几天开始传统方法和油猴脚本都上不去了，请问是什么原因导致的？账号失效？浏览器更新？代码更新导致失效？还是E站本身更新了机制
> > 求救
> 
> 巧了 我的也是这几天上不去的 老账号翻了一下好像已经没有igneous了好像

难受啊马飞

**Comment by luoyangyang2001** [comment]
> > > > 创建私人账号时找不到igneous是怎么回事
> > > 
> > > 
> > > igneous是在EX界面才有，EH没有的，而且新账号一周内igneous是无效的
> > 
> > 
> > 但是不找到igneous制作熊猫书签我怎么进入ex界面呢，大佬求指导
> 
> 注册账号后，等七天，直接进入EX，这个时候大概率是白屏，然后F12，查COOKEY，然后里面就能看到igneous了

igneous的变量是mystery是不是算申请失败了还是等7天后才会出

**Comment by PAG341CRR** [comment]
同问，新注册的号igneous显示mystery，进里站还是白屏没有熊猫，这样是注册失败还是等一周就行了

**Comment by Minepig** [comment]
> 同问，新注册的号igneous显示mystery，进里站还是白屏没有熊猫，这样是注册失败还是等一周就行了

igneous显示mystery就是无权限，新注册至少等两周
另外现在里站没有熊猫了，只有白屏

**Comment by luoyangyang2001** [comment]
> > 同问，新注册的号igneous显示mystery，进里站还是白屏没有熊猫，这样是注册失败还是等一周就行了
> 
> igneous显示mystery就是无权限，新注册至少等两周
> 另外现在里站没有熊猫了，只有白屏

至少两周么，我现在刚好七天，若是一个月后还没有igneous是不就说明无里区权限了

**Comment by noprogramming** [comment]
> 
> 
> > > 同问，新注册的号igneous显示mystery，进里站还是白屏没有熊猫，这样是注册失败还是等一周就行了
> > 
> > 
> > igneous显示mystery就是无权限，新注册至少等两周
> > 另外现在里站没有熊猫了，只有白屏
> 
> 至少两周么，我现在刚好七天，若是一个月后还没有igneous是不就说明无里区权限了

是的，这种就是没权限了。
