### ISSUE TITLE
公共书签又崩了吗？

### ISSUE THREAD

**Issue by dango1dango1** [ehpanda/expanda.org#23]
18：00 左右 公共账号似乎又被GANK了，这次来的太快了吧，只坚持了5天？难顶

**Comment by dango1dango1** [comment]
我觉得要么是熊猫自己提升了某些检测，要么就是公共账号或书签被人暴力使用了。

**Comment by shellingford9** [comment]
是啊，这也太快了吧，我自己的号根本获取不了权限（几年前注册的），很伤

**Comment by skymkmk** [comment]
自己用VPS搭梯子算公共IP吗？如果不算这几天用Vultr搭一个试试

**Comment by changan931114** [comment]
你好，我试图制作私人书签，大概是
ipb_pass_hashipb_member_idxigneous的格式对吗？
但是不知道为什么，申请私人书签无效，进入网站时会反复弹出
无权访问，更换exkey的提示，直接将私人书签ID输入也没有效果
请问我的格式有问题吗？还是说现在书签暂时不能使用呢？

**Comment by Potato32** [comment]
聊天室管理不想再被麻烦了。

**Comment by skymkmk** [comment]
找管理员请求加权限吗？怎么说呢

**Comment by Potato32** [comment]
至少有希望。

**Comment by wsksks** [comment]
> 至少有希望。



> ## 我联系到站点管理员了, 快点！去这里然后/msg DJNoni 用户名。
> https://qchat.rizon.net/?channels=e-hentai
> 或者告诉我 不要等到他都下线了。
> 机会!
> 至少不用等那么久再注册一个。快点！

请问进了频道该怎么办呢？

**Comment by Potato32** [comment]
等等。

**Comment by skymkmk** [comment]
> ## 我联系到站点管理员了, 快点！去这里然后/msg DJNoni 用户名。
> https://qchat.rizon.net/?channels=e-hentai
> 或者告诉我 不要等到他都下线了。
> 机会!
> 
> 至少不用等那么久再注册一个。快点！

要不麻烦您帮我说一下，e站昵称是skymkmk。我进去后不知道说啥，也没看聊天室，被踢出来了

**Comment by Potato32** [comment]
exhentai 在那里是个违禁词........不要说

**Comment by Potato32** [comment]
Fz117是公号的名吗？
不是的话。我不解。

**Comment by fz117** [comment]
> Fz117是公号的名吗？
> 不是的话。我不解。

那是我的eh私号，不过一直进不去ex，看了你的回复想去联系一下看看，结果想了想又不知道说什么，最后就直接退出去了。。。

**Comment by Potato32** [comment]
expanda 开发者呢？

**Comment by yyyps** [comment]
> expanda开发者呢？
能帮我解一下吗，昵称是xuxiaowei457896068

**Comment by Potato32** [comment]
不要私用账号好不好？

**Comment by Potato32** [comment]
更多人在用的公号。

**Comment by fz117** [comment]
> expanda 开发者呢？

找开发者你要去  “公共书签即将告罄”  里找更好吧

**Comment by enjoylife2233** [comment]
土豆在申请公共账号，不是私人的，别发自己的id了，dj管理员说了，私人账号不做处理

**Comment by wsksks** [comment]
> 更多人在用的公号。

谢谢您。

**Comment by Potato32** [comment]
....需要等个几天。那个是聊天室的管理员, 需要等群主也就是tenboro做出反应。不过比在注册更强。

**Comment by fz117** [comment]
> 要等个几天。那个是聊天室的管理员, 需要等群主也就是tenboro做出反应。不过比在注册更

所以联系到开发者了吗?你可能是全村的希望了啊

**Comment by Potato32** [comment]
估计还能得到官方的承认。
如果tenboro同意的话，

**Comment by Potato32** [comment]
至少比不去问要强。

**Comment by dango1dango1** [comment]
你知道公号名吗，怎么知道的 ------------------ 原始邮件 ------------------
发件人: "Potato32"<notifications@github.com>
发送时间: 2020年3月29日(星期天) 下午4:18
收件人: "noprogramming/expanda"<expanda@noreply.github.com>;
抄送: "dango1dango1"<3060594645@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [noprogramming/expanda] 公共书签又崩了吗？ (#23)




 
至少比不去问要强。
 
&mdash;

**Comment by PAG341CRR** [comment]
等待修复

**Comment by neallllll** [comment]
我注册了私人账户 但是一直显示拒绝我的访问 咋回事

**Comment by PAG341CRR** [comment]
我注册完后连论坛都登不上，比你还惨

neallllll <notifications@github.com> 于2020年3月29日周日 下午9:50写道：

**Comment by passlike** [comment]
光是需要欧美私人ip注册才能获得里区权限就已经能打死99%的国内人了吧，太难了

**Comment by DavidXie03** [comment]
> 光是需要欧美私人ip注册才能获得里区权限就已经能打死99%的国内人了吧，太难了

请问私人ip现在有什么途径能得到吗

**Comment by Potato32** [comment]
再弄一个邮箱。以及找你的外国朋友给你大概几分钟VPN到他家电脑的连接时间。

**Comment by Eric0508** [comment]
中國的朋友們 我是用windscribe成功註冊的
開著VPN掛美國後使用google帳號註冊
我瀏覽器是繁體中文
然後期間偶爾上線看個一兩本＋玩他的遊戲
等了大約10天後再掛一次VPN
登入表站 再改網站
連cookie都沒刪
就成功登入了
注意的是每台裝置第一次登入都需要掛VPN
不然chrom會黑屏 safari會白屏

現在創了第二個帳號
如果成功了會再貢獻出來
祝大家好運<3

**Comment by wsksks** [comment]
> 中國的朋友們 我是用windscribe成功註冊的
> 開著VPN掛美國後使用google帳號註冊
> 我瀏覽器是繁體中文
> 然後期間偶爾上線看個一兩本＋玩他的遊戲
> 等了大約10天後再掛一次VPN
> 登入表站 再改網站
> 連cookie都沒刪
> 就成功登入了
> 注意的是每台裝置第一次登入都需要掛VPN
> 不然chrom會黑屏 safari會白屏
> 
> 現在創了第二個帳號
> 如果成功了會再貢獻出來
> 祝大家好運<3

Thanks bro <3

**Comment by noprogramming** [comment]
> 
> 
> > 至少有希望。
> 
> > ## 我联系到站点管理员了, 快点！去这里然后/msg DJNoni 用户名。
> > https://qchat.rizon.net/?channels=e-hentai
> > 或者告诉我 不要等到他都下线了。
> > 机会!
> > 至少不用等那么久再注册一个。快点！
> 
> 请问进了频道该怎么办呢？

这些消息都不是我发的，这几天没上线。
公号现在已经被EX官方盯上了，新换的直接封号，没啥用了。
请各位自己注册私号吧，刚注册的没有权限的，要等两周。

**Comment by passlike** [comment]
> 中國的朋友們 我是用windscribe成功註冊的
> 開著VPN掛美國後使用google帳號註冊
> 我瀏覽器是繁體中文
> 然後期間偶爾上線看個一兩本＋玩他的遊戲
> 等了大約10天後再掛一次VPN
> 登入表站 再改網站
> 連cookie都沒刪
> 就成功登入了
> 注意的是每台裝置第一次登入都需要掛VPN
> 不然chrom會黑屏 safari會白屏
> 
> 現在創了第二個帳號
> 如果成功了會再貢獻出來
> 祝大家好運<3

感謝感謝，這就去試試

**Comment by noprogramming** [comment]
> 
> 
> 估计还能得到官方的承认。
> 如果tenboro同意的话，

感谢老哥，但我感觉官方都这么封号了，不可能允许一号多用的。
实际上公共账号模式是在破坏E站官方的P2P体系，他们严打的就是这种。
