### ISSUE TITLE
使用油猴登陸的帳戶是共用帳戶?

### ISSUE THREAD

**Issue by Jiang0712** [ehpanda/expanda.org#25]

**Comment by Jiang0712** [comment]
因為我的帳戶會多出我沒看過的收藏

**Comment by TkzcM** [comment]
未输入exkey时使用公共账号

**Comment by Jiang0712** [comment]
有啊我使用了油猴的插件進入里站 並且複製了COOKIE 組成密鑰

**Comment by Jiang0712** [comment]
也有使用
![未命名](https://user-images.githubusercontent.com/63041455/78338698-d291d080-75c5-11ea-93c4-67d1b816620a.png)
登入
在複製cookie組成密鑰
這樣獲得的密鑰也是公共帳號?

**Comment by Jiang0712** [comment]
但是cookie好像都是一樣的

可以進里站
這樣是不是都是公共帳號?

**Comment by Jiang0712** [comment]
![image](https://user-images.githubusercontent.com/63041455/78339694-7760dd80-75c7-11ea-9c38-247af9fe81f0.png)
這也是公共帳號?

**Comment by Jiang0712** [comment]
但是我並沒有看到那幾些組成密鑰的變數

**Comment by TkzcM** [comment]
未填写密钥时使用熊猫书签进入后是公共账号
复制出的cookies也是公共账号的cookies
可以和js前两行比对 相同即为公共账号
https://panda.52linglong.com/panda.js
如果不同，建议更换密码

**Comment by Jiang0712** [comment]
d9a945052c952334dd5d252b0c7388963552014x0745cd567

7a245abd0fa9866ccdfeaf58ff7dd0fd3552014xcc246e753
跟上面那兩個都不一樣

**Comment by Jiang0712** [comment]
油猴插件登入的要去哪裡改密碼呢

**Comment by Jiang0712** [comment]
註冊時一定要掛歐美vpn?
我沒掛vpn在論壇註冊了那要去哪看cookie呢?
我似乎沒看到那些密鑰所需的變數
![](https://user-images.githubusercontent.com/63041455/78339694-7760dd80-75c7-11ea-9c38-247af9fe81f0.png)

**Comment by TkzcM** [comment]
如果你不知道账号的密码，那基本就是公共账号了
注册时未使用欧美原生 IP 会无权限进入里站
密钥使用 ipb_member_id ipb_pass_hash igneous 三者拼接
如 igneous 为 mystery 则无权限

**Comment by Jiang0712** [comment]
1.8版

**Comment by Jiang0712** [comment]
那如果在這個https://forums.e-hentai.org/?act=Reg  論壇註冊完,一樣從論壇看cookie?
還是要去哪里看?

**Comment by Jiang0712** [comment]
![image](https://user-images.githubusercontent.com/63041455/78358861-7b502800-75e6-11ea-9f2a-fc00b682abe8.png)
我先登進表站但是並沒有看到igneous變數 
還是我應該先等一個禮拜
