### ISSUE TITLE
白屏问题，已经换了V，但是没用

### ISSUE THREAD

**Issue by Beansdz** [ehpanda/expanda.org#7]
我之前可以裸连上EX，现在去看是直接白屏（换了V也没用= =），是因为这几天特殊吗？

**Comment by Shironaus** [comment]
我也是（´_ゝ`）

**Comment by noprogramming** [comment]
白屏是E站主动拦截，你的IP属于不受欢迎的范畴。裸连就重启路由换IP，挂梯子就换个地区IP。日本的IP肯定白屏。

**Comment by BlueFlo0d** [comment]
确定不是 key 的问题吗？我在米帝也是白屏

**Comment by noprogramming** [comment]
> 
> 
> 确定不是 key 的问题吗？我在米帝也是白屏

白屏拦截是在验证COOKIE之前，想测试这个的话，关掉书签，清空COOKIE，
进：https://exhentai.org （一定是https）
看看是白屏还是道别的那张图，一般来说依然是白屏，说明IP被拦截了。
出现白屏是用了可疑的IP段，跟国内外没关系，一般是用公共VPN（或者公共咖啡馆）导致被拦截。
某个IP段使用的人过多，也会被拦截。这个属于书签机制外的问题了，解决办法只有换IP。

**Comment by noprogramming** [comment]
欧美主要是看服务商还有地区，因为E站内容在某些地区属于非法，所以采取了主动屏蔽IP来保证用户安全。以下几种情况容易被白屏：
1. 国外在咖啡馆、机场这类公共场合，看E站属于公众淫乱。
2. 在日本一类版权受限地区，怕被作者投诉所以屏蔽了他们的IP。
3. 英国、加拿大这类限制想象的国家，某些审查严格的网络服务商。
4. 美国某些清教州，比如犹他州。纽约、洛杉矶这类没问题，亲测。

**Comment by dango260** [comment]
那请问人在日本，电脑登录exhentai可以打开，手机登录就白屏改怎么解决啊(-᷅_-᷄)

**Comment by noprogramming** [comment]
> 
> 
> 那请问人在日本，电脑登录exhentai可以打开，手机登录就白屏改怎么解决啊(-᷅_-᷄)

那也是因为某些原因被拦截了，只能换个网络或者挂个VPN咯。另外确认下是不是走的 https:// 进的里站，如果http的话也会白屏。

**Comment by FlatKenshi** [comment]
我换阿根廷梯后登成功了
