### ISSUE TITLE
登陆以后积分下载显示err

### ISSUE THREAD

**Issue by keevinzha** [ehpanda/expanda.org#8]
点击Archive Download，settings，myupload都显示err，只能用bt下载，vpn是我自己搭的vultr

**Comment by noprogramming** [comment]
出现err说明用的还是公共号。咋登录的？
如果是绑定exkey我测试没问题。绑定后记得从expanda.org那个入口访问下，自动覆盖原有COOKIE。
如果是官网登录那应该是账户没权限，书签自动激活了公共号。测试自己账号有没有权限：
1. 关掉油猴插件/停用书签。
2. 清空浏览器COOKIE。
3. 挂梯子。
4. 从E表站首页登录自己的账号。
5. 加https进E里站官方地址，看能不能顺利进入。
6. 能顺利进入说明有权限，测试下能不能下载archive，能的话再开书签用竖屏功能啥的。

**Comment by keevinzha** [comment]
谢谢老哥，还有个问题，这几天为什么挂自己的欧洲梯子也是白屏，只能用书签的链接才能进去

**Comment by keevinzha** [comment]
换了好多ip还是白屏，纽约的ip也试了，感觉是vultr的问题，老哥有推荐的服务商吗

**Comment by keevinzha** [comment]
用书签上面那个链接能进去，直接用网址就白了

**Comment by noprogramming** [comment]
> 
> 
> 用书签上面那个链接能进去，直接用网址就白了

那不是E站拦截的白屏，是直接访问无效，本来应该是无法解析，因为你套了VPN所以被替换成了白屏。就用书签上面那个地址访问吧，或者用https访问E站。

**Comment by keevinzha** [comment]
大佬，我用表站的pass_hash和member_id加上公共书签的igneous拼成密钥能用我的账号进里站吗

**Comment by baysonfox** [comment]
> 大佬，我用表站的pass_hash和member_id加上公共书签的igneous拼成密钥能用我的账号进里站吗

我觉得不行

**Comment by noprogramming** [comment]
> 
> 
> 大佬，我用表站的pass_hash和member_id加上公共书签的igneous拼成密钥能用我的账号进里站吗

肯定不行，igneous是pass_hash和member_id的校验码，不一样压根不能登进去。
只能先用官方的办法成功登录里站（账号必须有权限），然后再提取igneous。

**Comment by keevinzha** [comment]
> > 大佬，我用表站的pass_hash和member_id加上公共书签的igneous拼成密钥能用我的账号进里站吗
> 
> 肯定不行，igneous是pass_hash和member_id的校验码，不一样压根不能登进去。
> 只能先用官方的办法成功登录里站（账号必须有权限），然后再提取igneous。

今天突然就能直接进去了，谢谢大佬，我试了下添加ex站的host，不知道和这个有没有关系
