### ISSUE TITLE
脚本无法第一时间启动，等到forum页面验证完了之后才启动，结果就是进不去

### ISSUE THREAD

**Issue by Macaron-Lawrence** [ehpanda/expanda.org#9]
直接输入 https://exhentai.org 的情况下，油猴脚本显示无脚本载入。此时exhentai跳转forum登陆验证，验证失败后出现白屏，此时油猴脚本才显示熊猫书签已加载

结果就是进不去

但是如果输入 https://exhentai.org/favicon.ico 的话，e站会跳出来E.H的小图标，这个时候油猴脚本显示脚本被加载，接着小图标会消失跳转exhentai并且成功进入exhentai。

应该是个不知道哪里的问题的小Bug。希望修复一下

**Comment by noprogramming** [comment]
不是BUG，说明里写了中国大陆只能从： expanda.org ，顶部链接： https://exhentai.org/favicon.ico （直接走这个顶部链接也行），进入里站。
直接进ex会跳转到论坛验证接口，这个接口被墙所以卡死了。油猴机制是在页面加载前无法开启，所以靠书签脚本无法修复的。

**Comment by Macaron-Lawrence** [comment]
明白了谢谢
